name: hidden_intelligence
description: "A Game with Trust Issues!"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  device_info_plus: ^10.1.2
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.4.3
  google_generative_ai: ^0.4.6
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.2.0
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  games_services: ^4.0.2
  go_router: ^14.2.9
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - .env
    - lib/resources/
  fonts:
    - family: Inconsolata
      fonts:
        - asset: lib/resources/fonts/Inconsolata-Black.ttf
          weight: 800
          style: normal
        - asset: lib/resources/fonts/Inconsolata-ExtraBold.ttf
          weight: 700
          style: normal
        - asset: lib/resources/fonts/Inconsolata-Bold.ttf
          weight: 600
          style: normal
        - asset: lib/resources/fonts/Inconsolata-SemiBold.ttf
          weight: 500
          style: normal
        - asset: lib/resources/fonts/Inconsolata-Medium.ttf
          weight: 400
          style: normal
        - asset: lib/resources/fonts/Inconsolata-Regular.ttf
          style: normal
          weight: 300
        - asset: lib/resources/fonts/Inconsolata-Light.ttf
          weight: 200
          style: normal
        - asset: lib/resources/fonts/Inconsolata-ExtraLight.ttf
          weight: 100
          style: normal
  uses-material-design: true